scaling: update golden files
sourcegraph/resource-estimator pull request #15
Opened 2022-06-28 21:07 UTC by keegancsmith

The last commit broke the tests, but we aren't running go tests in CI to
notice. This commit fixes that.

Test Plan: go test ./...

2022-06-28 21:16 UTC, abeatrix approved these changes
Wasn't aware of this, thank you so much!

2022-06-28 21:20 UTC, abeatrix requested changes
I just realize I broke something in my last commit so all the default values also have the ꜝ added to the end. I'm working on a PR to fix that now

2022-06-28 21:20 UTC, abeatrix commented on internal/scaling/testdata/TestEstimate/default.golden
> +| zoekt-webserver | 1ꜝ | - | 8ꜝ | - | 10gꜝ |
```suggestion
| zoekt-webserver | 1 | - | 8 | - | 10gꜝ |
```

I just realize I broke something in the last commit so all the default values are also added ꜝ to the end. I 'm working on a PR to fix it now

2022-06-29 07:02 UTC, keegancsmith commented
I'm glad the tests are already adding value. Now all we need is CI to tell us lol.

2022-06-29 07:03 UTC, keegancsmith commented
@abeatrix FYI you can run `go test -update` in the scaling dir to update the tests.

2022-06-29 07:04 UTC, merged